spring:
  application:
    name: Vroom
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: create-drop
  liquibase:
    enabled: false
    change-log: db/changelog/master.yaml
  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start-only
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    password: f7a4964915afd3
    username: 553860333d6328
server:
  port: 8082
  servlet:
      context-path: /api/v1