spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Vroom
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
    change-log: db/changelog/master.yaml
  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start-only
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    password: f7a4964915afd3
    username: 553860333d6328

cloud:
  aws:
    credentials:
      access-key: AKIAYHJANMV6HVGFFT4N
      secret-key: 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
    region:
      static: eu-west-3

application:
  bucket:
    name: vrooma

server:
  port: 8082
  servlet:
    context-path: /api/v1
