version: '3.8'

name: vroom
services:
  postgres:
    container_name: vroom_db
    image: 'postgres:17'
    environment:
      POSTGRES_DB: vroom
      POSTGRES_USER: vroom
      POSTGRES_PASSWORD: vroom
    ports:
      - '5433:5432'
volumes:
  postgres_data:
    driver: local
